### PR TITLE
introduce the `--pull` option mirroring `--no-cache`

### PR DESCRIPTION
**Pull request by cruwe**
First, thank you very much for developing this plugin and allowing the public to profit from your work.

For the plugin to selectively force pull the `FROM` image, I mirrored the config forthe related `--no-cache`. I hope I do not mess up your intended organization.

Thanks again and cheers!

### CODE REVIEW

**Comment by lexemmens** [comment]
Hi Christopher,

Thank you so much for your kind words! I really appreciate it. Making this publicly available was the least I could do as I wondered that others could benefit from this plugin as well :-)

As far as your changes are concerned, thanks again for taking the time to contribute in improving this plugin. I do, however, have a few comments, which I'll put below.

**Review by lexemmens — CHANGES_REQUESTED** [review]
WIth respect to the new `pull` parameter, the current default behavior is that it will evaluate to false, when it is not explicitly set using configuration. However, according to the [documentation](https://www.redhat.com/sysadmin/podman-image-pulling) the default value is true unless explicitly set.

I would really appreciate it if you could change it so that the default value will be true, unless explicitly configured in the pom file. This can be achieved by making this property nullable, e.g by changing `boolean` to `Boolean`, and check its value in the `#validate` method.

**Comment by cruwe** [comment]
Hi, thank you for your positive attitude. As requested I (hopefully correctly) reversed the default behaviour of the `--pull` option to be inline with `podman` defaults, Please excuse that I did not read the docs in depth - just (and here wrongly) assumed the docker-defaults. Thanks again! Cheers!

**Comment by lexemmens** [comment]
> Hi, thank you for your positive attitude. As requested I (hopefully correctly) reversed the default behaviour of the `--pull` option to be inline with `podman` defaults, Please excuse that I did not read the docs in depth - just (and here wrongly) assumed the docker-defaults. Thanks again! Cheers!

Thanks for the update on the PR. I don't think I expressed that very clear in the documentation, no worries. I still need to update the documentation on that.

As far as the code change in this PR is concerted: I tested it locally and it looks good to me! I will update the docs, merge this PR and then make a release out of this. I will credit you in the 

Thanks again for your contribution!

**Review by lexemmens — APPROVED** [review]

**Pull request merged**
